# Generated by Django 5.1.5 on 2025-02-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/BookStore/images/')),
                ('file', models.FileField(upload_to='static/BookStore/books/')),
                ('category', models.CharField(choices=[('guides', 'كتب إرشادية'), ('reports', 'تقارير فنية'), ('research', 'ابحاث علمية')], max_length=50)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
