# Generated by Django 5.1.6 on 2025-02-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QServices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='./static/QServices/images/'),
        ),
    ]
