# Generated by Django 5.1.5 on 2025-02-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to='./static/QProducts/images/')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='./static/QProducts/images/')),
            ],
        ),
    ]
